name = "docushare-api-dev"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-09-01"
kv_namespaces = [
    { binding = "USERS", id = "3386f9541ff24fd9a1345b270ae4516b" },
    { binding = "DOCS", id = "884163eb762140359e3778f2a2a9c07d" }
]
vars = { ENV = "dev" }

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[env.staging]
name = "docushare-api-staging"
vars = { ENV = "staging" }
kv_namespaces = [
    { binding = "USERS", id = "ad548ba072754862808a2189484f9ef9" },
    { binding = "DOCS", id = "f55be1b60e204892903f0da19aa1d332" }
]

[env.production]
name = "docushare-api"
workers_dev = false
route = "docushare-api.matteopaz.me/*"
zone_id = "f0751e95ee874a4ca5479cd279b7b12b"
kv_namespaces = [
    { binding = "USERS", id = "111931f112664264ba0f8b33d5090e73" },
    { binding = "DOCS", id = "387f014947a24be6bde102829932a49b" }
]
vars = { ENV = "prod" }
