name = "docushare-api"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-09-01"
kv_namespaces = [
    { binding = "USERS", id = "bf2090401a9f42bd8067ee06ba07855d" },
    { binding = "DOCS", id = "99b287205a41478f843e17eff9070386" }
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
